services:
  # client:
  #   build: ./client
  #   ports:
  #     - "80:80"
  #   env_file:
  #     - .env
    
  server:
    build: ./server
    ports:
      - "3001:3001"
    networks:
      my_network:
        ipv4_address: 172.18.0.22
    env_file:
      - .env
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_DATABASE}

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
        